### ISSUE TITLE
End time when charging not in correct timezone.

### ISSUE THREAD

**Issue by CrazyHenk44** [robske110/IDDataLogger#25]
When charging (not finished), the end time appears in 2h in the future, probably not respecting my time zone. After finishing it shows the correct time in my timezone.

**Comment by robske110** [comment]
Which browser (and which version) are you using? I am unfortunately unable to reproduce this behaviour, but I have had reports of this issue already.

**Comment by CrazyHenk44** [comment]
I'm on an Opera browser:

Versie:78.0.4093.147 (x86_64)
Updatestream:Stable
Systeem:macOS Versie 11.5.2 (build 20G95) 11.5.2 x86_64

I've looked at the log, but can't find anything interesting there:

`
Aug 31 17:28:38 omat iddatalogger[32521]: 17:28:38.812838 [INFO] Building past charge sessions from beginning of data logging...
Aug 31 17:28:38 omat iddatalogger[32521]: 17:28:38.813590 [INFO] Plugged car in at 2021-08-31 15:28:29
Aug 31 17:28:38 omat iddatalogger[32521]: Loading ChargeSession...
Aug 31 17:28:38 omat iddatalogger[32521]: 17:28:38.814236 [INFO] Started charging at 2021-08-31 15:28:29
Aug 31 17:28:38 omat iddatalogger[32521]: Loading CarStatusFetcher...
Aug 31 17:28:38 omat iddatalogger[32521]: 17:28:38.814891 [INFO] Logging in...
Aug 31 17:28:38 omat iddatalogger[32521]: Loading LoginInformation...
Aug 31 17:28:38 omat iddatalogger[32521]: Loading MobileAppAPI...
Aug 31 17:28:38 omat iddatalogger[32521]: Loading HTTPUtils...
Aug 31 17:28:39 omat iddatalogger[32521]: Loading Form...
Aug 31 17:28:41 omat iddatalogger[32521]: Loading CarStatusUpdateReceiver...
Aug 31 17:28:41 omat iddatalogger[32521]: Loading CarStatusWriter...
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.435974 [INFO] Done. Startup took 2.800448179245s
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.436101 [INFO] Ready!
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.436199 [INFO] Fetching car status...
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.981114 [NOTICE] Could not find expected key 'zoneRearLeftEnabled' in carStatusData. Unexpected
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.981369 [NOTICE] Could not find expected key 'zoneRearRightEnabled' in carStatusData. Unexpecte
Aug 31 17:28:41 omat iddatalogger[32521]: 17:28:41.981445 [INFO] Writing new data for timestamp 2021-08-31T15:28:29
[...snip repeats...]
Aug 31 17:37:41 omat iddatalogger[32521]: 17:37:41.872550 [INFO] Unplugged car at 2021-08-31T15:37:03
Aug 31 17:37:41 omat iddatalogger[32521]: 17:37:41.872623 [INFO] Charge session:
Aug 31 17:37:41 omat iddatalogger[32521]: range: start: 239km end: 240km
Aug 31 17:37:41 omat iddatalogger[32521]: duration: 0.1h
Aug 31 17:37:41 omat iddatalogger[32521]: SOC: start: 69% end: 69% target: 80%
Aug 31 17:37:41 omat iddatalogger[32521]: chargeEnergy:0.26kWh cE_soc_calc0kWh
Aug 31 17:37:41 omat iddatalogger[32521]: POWER: avg: 2kW min: 2kW max: 2kW
`

**Comment by robske110** [comment]
This was unfortunately also a bug related to MySQL. I will consider officially deprecate mysql, it is simply too much extra work and very hard to test edge cases like this. (Even with proper tests, this would have been very hard to catch)

The bug was caused by a missing NULL declaration for the endTime field causing MySQL to automatically fill in the current time if a new row was created. This also might have also split charging sessions, if IDDataLogger was restarted during one. (Because of this I simply recommend deleting the whole table)

For everyone affected by this bug, you'll need to DROP TABLE chargingSessions and recreate it using this new SQL: https://github.com/robske110/IDDataLogger/blob/master/db_mysql.sql#L43-L59
Don't worry, the chargingSessions will be regenerated from the data in the carStatus table.

**Comment by CrazyHenk44** [comment]
Thank you and thanks for the instructions to repair it. Please don't drop mysql support, I'm happy to test for you,  and I can also create issues if I run into them.
