### ISSUE TITLE
Kein Zugriff auf Weboberfläche

### ISSUE THREAD

**Issue by Raczka1989** [robske110/IDDataLogger#58]
Hallo ich habe mir den Datalogger auf meinem Synnas Installiert über Docker aber das Problem is das ich kein Zugriff auf die Weboberfläche habe kann mir jemand weiterhelfen?
Diese Meldung kommt sobald ich darauf zugreifen will im Terminal
iddatalogger_web | [Tue Apr 23 20:47:16.300030 2024] [php:warn] [pid 16] [client 172.18.0.1:49354] PHP Warning: Unknown: Failed to open stream: Permission denied in Unknown on line 0
iddatalogger_web | [Tue Apr 23 20:47:16.300052 2024] [php:error] [pid 16] [client 172.18.0.1:49354] PHP Fatal error: Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0
iddatalogger_web | 172.18.0.1 - - [23/Apr/2024:20:47:16 +0000] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
iddatalogger_web | 172.18.0.1 - - [23/Apr/2024:20:47:22 +0000] "GET /vwid HTTP/1.1" 404 495 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

**Comment by robske110** [comment]
Just for visibility, this was resolved on the forum with the following commands:
[CODE]
cd /path/to/IDDataLogger
chmod -R a=r,u+w,a+X ./public/
cd docker
docker-compose build web
docker-compose up
[/CODE]
The existing permissions in the build environment matter, because the COPY command (used [here](https://github.com/robske110/IDDataLogger/blob/master/docker/Dockerfile-web#L9)) copies the permissions into the container.
